<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\YellowCola.Cart.Application\YellowCola.Cart.Application.csproj" />
    <ProjectReference Include="..\YellowCola.Cart.Infrastructure\YellowCola.Cart.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
