<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YellowCola.Catalog.Application\YellowCola.Catalog.Application.csproj" />
    <ProjectReference Include="..\YellowCola.Catalog.Infrastructure\YellowCola.Catalog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
