// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YellowCola.Inventory.Infrastructure.Persistence;

#nullable disable

namespace YellowCola.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YellowCola.Inventory.Domain.InventoryItems.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("warehouse_code");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_items_warehouse_code_sku_id");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_items_on_hand_non_negative", "\"on_hand\" >= 0");

                            t.HasCheckConstraint("CK_inventory_items_reserved_non_negative", "\"reserved\" >= 0");

                            t.HasCheckConstraint("CK_inventory_items_reserved_not_greater_than_on_hand", "\"reserved\" <= \"on_hand\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
